resove fixme for lateral left join in partition_join.sql (#15492)
GPDB does not support the Lateral feature officially.
some of the lateral features do work well, such as:
```
create table t1(Tc1 int, tc2 int);
create table t2(Tc3 int, tc4 int);
explain SELECT * FROM t1 LEFT JOIN LATERAL
                                 (SELECT a.tc3, least(t1.tc1,a.tc3) from t2 a) ss
                                 ON t1.tc1=ss.tc3;
```
we specify the keyword LATERAL to indicate in subquery we can use the column of t1.
Above join do not need motion between t1 and ss. So it can work well.

However, some of the lateral features do not work well, such as the following sql:
```
create table t1(Tc1 int, tc2 int);
create table t2(Tc3 int, tc4 int);

explain SELECT * FROM t1 LEFT JOIN LATERAL
                                 (SELECT a.tc3, a.tc4, least(t1.tc1, a.tc3) from t2 a) ss
                                 ON t1.tc2=ss.tc4;
ERROR:  could not devise a query plan for the given query (pathnode.c:275)
```
If the inner path uses column of outer path, We can not add motion above inner path.
however, in left join, outer path can not be replicated. We can not generate path for left join,
So hit the error.

Change the GPDB_12_MERGE_FIXME to GPDB_12_MERGE_FEATURE_NOT_SUPPORTED for
lateral test in partition_join.sql